
###
GET http://localHost:8080/api/Vehiculo

###
POST http://localhost:8080/api/Vehiculo
Content-Type: application/json

{
  "idVehiculo": 2,
  "tipoVehiculo": "Automóvil",
  "placa": "RNX330",
  "tipoServicio": "PUBLICO",
  "tipoCombustible": "GAS",
  "capacidadPasajeros": 5,
  "color": "#FF2FFF",
  "modelo": 2022,
  "marca": "Suzuki",
  "linea": "Gixxer",
  "documentos": [
    {
      "documento": {
        "idDocumento": 2
      },
      "fechaExpedicion": "2024-01-01",
      "fechaVencimiento": "2027-12-31"
    }
  ]
}
###
GET http://localHost:8080/api/Vehiculo/placa/DA212A
###
GET http://localHost:8080/api/Vehiculo/placa/DA212A

###
PUT http://localhost:8080/api/Vehiculo/1
Content-Type: application/json

{
    "idVehiculo": 1,
    "tipoVehiculo": "Motocicleta",
    "placa": "BOV18D",
    "tipoServicio": "PUBLICO",
    "tipoCombustible": "GAS",
    "capacidadPasajeros": 2,
    "color": "#8e89cc",
    "modelo": 2022,
    "marca": "Suzuki",
    "linea": "Gixxer"
}

###
DELETE http://localHost:8080/api/Vehiculo/1
